version: '3'

services:
  dev:
    build: 
      context: .
      dockerfile: ./development/Dockerfile
    image: boto3_dev
    environment:
      ENVIRONMENT: dev
    volumes:
      - type: bind
        source: ./development
        target: /home/app
    networks:
      - dev_net

  prodA:
    build:
      context: .
      dockerfile: ./productionA/Dockerfile
    image: boto3_prod_a
    environment:
      ENVIRONMENT: prod
    networks:
      - prod_net

  prodB:
    build: 
      context: .
      dockerfile: ./productionB/Dockerfile
    image: boto3_prod_b
    environment:
      ENVIRONMENT: prod
    networks:
      - prod_net

networks:
  prod_net:
  dev_net:
   

      


