version: '3'

services:
  dev:
    build: 
      context: /development
      dockerfile: Dockerfile
    image: boto3_dev
    environment:
      ENVIRONMENT: dev
    volumes:
      - ./development/scripts
    networks:
      - boto3_dev_net

  prodA:
    build: 
      context: /productionA
      dockerfile: Dockerfile
    image: boto3_prodA
    environment:
      ENVIRONMENT: prod
    networks:
      - boto3_prod_net

  prodB:
    build: 
      context: /productionB
      dockerfile: Dockerfile
    image: boto3_prodB
    environment:
      ENVIRONMENT: prod
    networks:
      - boto3_prod_net

networks:
  boto3_prod_net:
  boto3_dev_net:

      


